---
- name: Get Ubuntu codename
  command: lsb_release -cs
  register: command_output

- name: Set Ubuntu codename
  set_fact:
    lsb_release: "{{command_output.stdout}}"

- name: Get kernel name
  command: uname -s
  register: command_output

- name: Set kernel name
  set_fact:
    kernel: "{{command_output.stdout}}"

- name: Get machine
  command: uname -m
  register: command_output

- name: Set machine
  set_fact:
    machine: "{{command_output.stdout}}"

- name: Add Docker’s official GPG key
  apt_key:
    url: https://yum.dockerproject.org/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb http://apt.dockerproject.org/repo/ ubuntu-{{ lsb_release }} main

- name: Install Docker
  become: yes
  apt: name=docker-engine state=latest

- name: Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.10.0/docker-compose-{{ kernel }}-{{ machine }}
    dest: /usr/local/bin/docker-compose
    mode: 0755
