---
- name: Get Ubuntu codename
  command: lsb_release -cs
  register: command_output

- name: Set Ubuntu codename
  set_fact:
    lsb_release: "{{command_output.stdout}}"

- name: Add Docker’s official GPG key
  apt_key:
    url: https://yum.dockerproject.org/gpg

- name: Add Docker repository
  apt_repository:
    repo: deb http://apt.dockerproject.org/repo/ ubuntu-{{ lsb_release }} main

- name: Install Docker
  become: yes
  apt: name=docker-engine state=latest

- name: Build Dockerfile
  command: docker build -t mynginx:latest .

- name: Start Nginx in Docker
  command: docker run --name webserver -d -p 80:80 mynginx